post = Post.new(
  title: "Wildnis ist die natürliche Ordnung der Dinge",
  content_1: "Wenn Menschen zum ersten mal in Bezug auf Seminare mit dem Begriff in Berührung kommen, denken sie an Weite, unberührte Natur, jegliches Fehlen von Zivilisation, keinerlei  Müll und so weiter. Jedoch befindet sich Wildnis im ursprünglichen Sinne überall dort, wo der Mensch nicht eingreift, und das können 3 Quadratmeter Erde sein.",
  content_2: "Der Blumentopf kann sich zu einem mikroskopisch kleinen Biotop Wildnis verwandeln, wenn man ihn läßt. Es werden sich im Laufe des Jahres die Pflanzen und Tiere verändern, manche kommen, manche gehen, dazu braucht es mehr Neugier und Beobachtungsgabe als unbegrenzten Raum. Insofern meinen wir, wenn wir von” wilden Menschen” oder” in die Wildnis gehen” sprechen, keineswegs eine zweijährige Reise nach Alaska oder das Leben in einem Rudel wilder Wölfe, wir meinen damit lediglich, daß wir wieder lernen, uns in die Natur einzufügen, ein Teil zu werden und alles Überflüssige im Innen und Außen wegzulassen. Das bedeutet auch, daß sich unsere Ausrüstung minimieren wird, wir reisen zunehmend mit leichtem Gepäck, wir lernen Wesentliches von Unwesentlichem zu unterscheiden. Und das ist ein Weg, kein Ziel, sind wir doch alle immer Reisende in unserem Leben.",
  content_3: "Gerade was Outdoorausrüstung angeht ist der Markt in den letzten Jahren explodiert. Unentwegt kommen neue Materialien, neue Modelle, neue Hilfsmittel hinzu und wir scheinen in Angeboten zu ertrinken. Umso wichtiger ist es auch bei der Ausrüstung zu lernen, was es wirklich braucht und was durch Kreativität oder Naturmaterialien ersetzt werde kann.Das schont nicht nur den Geldbeutel sondern auch die Umwelt.",
  content_4: "Und “Wilde” sind keinesfalls Menschen, denen es an Respekt, Dankbarkeit, sozialem Miteinander oder  gemeinschaftlichen Übereinkünften mangelt, im Gegenteil: nur mit solchen Werkzeugen waren ursprüngliche Gemeinschaften überhaupt in der Lage, zu überleben. Sie waren Meister im Nähren und Fördern von allem, was Gemeinschaft stärkt, waren sie doch ohne diese dem Tode geweiht."
)

post.title_image.attach(io: File.open('app/assets/images/owl.jpg'), filename: "owl.jpg")
post.post_image_1.attach(io: File.open('app/assets/images/owl.jpg'), filename: "owl.jpg")
post.post_image_2.attach(io: File.open('app/assets/images/owl.jpg'), filename: "owl.jpg")
post.post_image_3.attach(io: File.open('app/assets/images/owl.jpg'), filename: "owl.jpg")
post.save!

post = Post.new(
  title: "Warum die Natur...?",
  content_1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Numquam modi corporis aspernatur cum ullam accusamus eligendi sit facere temporibus sequi vitae provident eum impedit, ea voluptates dignissimos. Deserunt laborum tempore impedit non veniam, incidunt facilis quis animi eos. Voluptatum impedit rem repellat quisquam iusto, natus, beatae tempora illum eaque iure aspernatur accusamus ratione in voluptates suscipit, pariatur temporibus a nesciunt reprehenderit? Illo iusto corporis ratione aliquid, voluptas id quasi unde expedita velit in possimus aut impedit! Similique nihil autem voluptatibus, ducimus vitae, omnis veniam voluptas delectus, architecto excepturi numquam consequuntur aut veritatis ipsum neque odio error fugiat eos suscipit iure.",
  content_2: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Numquam modi corporis aspernatur cum ullam accusamus eligendi sit facere temporibus sequi vitae provident eum impedit, ea voluptates dignissimos. Deserunt laborum tempore impedit non veniam, incidunt facilis quis animi eos. Voluptatum impedit rem repellat quisquam iusto, natus, beatae tempora illum eaque iure aspernatur accusamus ratione in voluptates suscipit, pariatur temporibus a nesciunt reprehenderit? Illo iusto corporis ratione aliquid, voluptas id quasi unde expedita velit in possimus aut impedit! Similique nihil autem voluptatibus, ducimus vitae, omnis veniam voluptas delectus, architecto excepturi numquam consequuntur aut veritatis ipsum neque odio error fugiat eos suscipit iure.",
  content_3: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Numquam modi corporis aspernatur cum ullam accusamus eligendi sit facere temporibus sequi vitae provident eum impedit, ea voluptates dignissimos. Deserunt laborum tempore impedit non veniam, incidunt facilis quis animi eos. Voluptatum impedit rem repellat quisquam iusto, natus, beatae tempora illum eaque iure aspernatur accusamus ratione in voluptates suscipit, pariatur temporibus a nesciunt reprehenderit? Illo iusto corporis ratione aliquid, voluptas id quasi unde expedita velit in possimus aut impedit! Similique nihil autem voluptatibus, ducimus vitae, omnis veniam voluptas delectus, architecto excepturi numquam consequuntur aut veritatis ipsum neque odio error fugiat eos suscipit iure.",
  content_4: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Numquam modi corporis aspernatur cum ullam accusamus eligendi sit facere temporibus sequi vitae provident eum impedit, ea voluptates dignissimos. Deserunt laborum tempore impedit non veniam, incidunt facilis quis animi eos. Voluptatum impedit rem repellat quisquam iusto, natus, beatae tempora illum eaque iure aspernatur accusamus ratione in voluptates suscipit, pariatur temporibus a nesciunt reprehenderit? Illo iusto corporis ratione aliquid, voluptas id quasi unde expedita velit in possimus aut impedit! Similique nihil autem voluptatibus, ducimus vitae, omnis veniam voluptas delectus, architecto excepturi numquam consequuntur aut veritatis ipsum neque odio error fugiat eos suscipit iure."
)

post.title_image.attach(io: File.open('app/assets/images/owl.jpg'), filename: "owl.jpg")
post.post_image_1.attach(io: File.open('app/assets/images/owl.jpg'), filename: "owl.jpg")
post.post_image_2.attach(io: File.open('app/assets/images/owl.jpg'), filename: "owl.jpg")
post.post_image_3.attach(io: File.open('app/assets/images/owl.jpg'), filename: "owl.jpg")
post.save!

puts "Posts created"
